### ISSUE TITLE
name of this repository is not describing what it actually is

### ISSUE THREAD

**Issue by thecotne** [Carrooi/Js-GoogleMapsLoader#15]
it's CommonJS wrapper around google map api
it's not for NodeJS

so why it's named "Node-GoogleMaps"

renaming repository does not cause any issues see https://help.github.com/articles/renaming-a-repository/

i suggest "google-maps-loader" (dash-case) or "googleMapsLoader" (camelCase)
i prefer dash-case names for repositories

**Comment by sakren** [comment]
"Node" is something like namespace for me. But for some time I want to somehow rename this package in npmjs and bower repositories to "google-maps-loader"

**Comment by sakren** [comment]
So maybe name of repository should be "Node-GoogleMapsLoader"

**Comment by thecotne** [comment]
namespace for your repositories is username or name of Organization

i don't like `Node-` prefix because it has nothing to do with node

**Comment by sakren** [comment]
So what do you think about "Js-GoogleMapsLoader"? You see I have 19 repositories under carrooi organization and 31 under my username which I'm currently trying to move under carrooi. So its 50 repositories and it's sometimes quite difficult to navigate throw them.

But you are also definitely right and I understand you.

**Comment by thecotne** [comment]
> So what do you think about "Js-GoogleMapsLoader"? 

it's much better
since it's javascript package `js` prefix is not confusing
and `GoogleMapsLoader` describes this package very well

**Comment by sakren** [comment]
Brilliant, so thanks for your help :wink:

**Comment by hollandmatt** [comment]
NPM generally advises not to use `js` in package names - it it's an NPM package, it's going to be javascript. (Mostly :wink: )

https://docs.npmjs.com/files/package.json

**Comment by sakren** [comment]
Yep, that would be quite stupid, so name of npm and bower packages will be `google-maps-loader` (now just `google-maps`). But we were mainly talking about GitHub repository, which I would like to rename to `Js-GoogleMapsLoader`.

**Comment by thecotne** [comment]
in most cases repository name is same as package name
it is also confusing to have `Js-GoogleMapsLoader` repository
which you can't install by `npm install Js-GoogleMapsLoader`

but as i mentioned `js` prefix is much better then `node`

**Comment by sakren** [comment]
I really understand, it's just the amount of repositories that bothers me... Otherwise I wouldn't name it like that at all. 

And to be honest, I don't like it too :stuck_out_tongue:

**Comment by thecotne** [comment]
you have sorted repositories list here http://www.davidkudera.com/projects/
you can link that page in organization URL
so it's easy to use that page instead of plain repositories list

**Comment by sakren** [comment]
Actually I'm thinking about removing that page.. But I'm not sure yet. Also removing node (and not adding js) prefix will mean than I should remove these prefixes from all other repositories and then I think that it will be complete mess.

But I'm not trying to defy everything you say, even thought it may look like it :wink:
