### ISSUE TITLE
NPM version is out of date

### ISSUE THREAD

**Issue by mattholland-dnb** [Carrooi/Js-GoogleMapsLoader#20]
Is it possible to push a new version to NPM? The latest release (3.0.0) does not include the language parameter support. Thanks. :)

**Comment by sakren** [comment]
hello, yes later today or tomorow :wink:

**Comment by sakren** [comment]
Hi, I just released new version 3.1.0, also sorry for such delay :wink:

**Comment by mattholland-dnb** [comment]
Thanks :smile_cat:
