### ISSUE TITLE
Promises API not supported.

### ISSUE THREAD

**Issue by AngeloGulina** [Carrooi/Js-GoogleMapsLoader#24]
I checked and this comes directly from the code.
The object I get back calling GoogleMapsLoader.load(...) still has promises interface instead (but with prototype: GoogleMapsLoader.load.promiseError). 

Why is that?

**Comment by davidkudera** [comment]
It's there only for back compatibility. At the begining this library used `q` promises, but this was in later releases.

I could probably remove it completly now.

https://github.com/Carrooi/Js-GoogleMapsLoader/commit/e7677e9be9c2bf0d14937168b8e5555a78123944
