### ISSUE TITLE
Warning. The sensor parameter is no longer required for the Google Maps JavaScript API.

### ISSUE THREAD

**Issue by kolegm** [Carrooi/Js-GoogleMapsLoader#29]
I get one warning from Google during the usage of the [module](github.com/Carrooi/Node-GoogleMaps.git#3.1.0)

*Warning*:
> "SensorNotRequired: https://developers.google.com/maps/documentation/javascript/error-messages"

**Comment by davidkudera** [comment]
Thank you.

There is already a PR for that: #28. Hopefuly I'll have enough time to merge this and release a new version this week.

**Comment by kbardi** [comment]
I have the same problem. My code is: 
GoogleMapsLoader.SENSOR     = false;
    GoogleMapsLoader.LIBRARIES = [ 'places' ];
    GoogleMapsLoader.load(function(google) {
      geocoderStatus = google.maps.GeocoderStatus;
      geocoder       = new google.maps.Geocoder();
    });

But it's still showing the SensorNotRequired warning. How can I avoid the warning or set the Sensor false? Thanks

**Comment by davidkudera** [comment]
I'll try to create a new pull request, since this problem seems pretty important and the current PR can not be merged..

**Comment by davidkudera** [comment]
Fixed with #34
