### ISSUE TITLE
The signature is missing, any plan to add it?

### ISSUE THREAD

**Issue by huangye177** [Carrooi/Js-GoogleMapsLoader#33]
Hi, it seems that the signature is missing, is there any plan to add it?

https://developers.google.com/maps/documentation/static-maps/get-api-key#client-id

Or, is the signature needed here (supposed to be used from browser? Or only used in server side?)

Cheers, 
Ye

**Comment by davidkudera** [comment]
Hi, it seems that google recomends to use signed urls only on server. You can read about it [here](https://developers.google.com/maps/premium/faq#signature_js)

**Comment by davidkudera** [comment]
Closing for now, write if you'll have any other questions :wink:
