### ISSUE TITLE
Marker Clustering library support?

### ISSUE THREAD

**Issue by gerardreches** [Carrooi/Js-GoogleMapsLoader#39]
Hi,

Is the use of marker clustering implemented on this package as an optional library?

Is there a list of the possible libraries that can be added to the array? It's difficult to know which are the specific syntax to include it, and also which are supported.

**Comment by davidkudera** [comment]
Hello, there is no direct support for marker clustering. But just like it's said [here](https://developers.google.com/maps/documentation/javascript/marker-clustering) you should import clustering library directly into your project. Then you can use this library for loading google maps itself

**Comment by davidkudera** [comment]
Closing for now. If you'll have some other questions, don't hesitate to ask :wink:
