### ISSUE TITLE
TypeError: Cannot read property 'resize' of undefined

### ISSUE THREAD

**Issue by Caoimhin89** [Carrooi/Js-GoogleMapsLoader#45]
Hi. I'm trying to make an api call to Google Maps from a Vue.js application with webpack.

In the Vue component where I attempt to make the call, I have the following code:

```
import GoogleMapsLoader from 'google-maps';
export default {
    data() {
      return {}
    },
    beforeCreate() {
      GoogleMapsLoader.KEY = 'BIzaSyBBDsSK&&&6TFjSfRkUn8BP####NszLo';
      GoogleMapsLoader.load(function(google) {
        new google.maps.Map('#map')
      });
    }
  }
```

And this is the stack trace I get in Chrome DevTools:

`js?callback=__google_maps_api_provider_initializator__:38 Uncaught TypeError: Cannot read property 'resize' of undefined(…)ob @ js?callback=__google_maps_api_provider_initializator__:38vb @ js?callback=__google_maps_api_provider_initializator__:39_.z.addListener @ js?callback=__google_maps_api_provider_initializator__:97_.z.forward @ js?callback=__google_maps_api_provider_initializator__:99Oy.f @ map.js:46(anonymous function) @ js?callback=__google_maps_api_provider_initializator__:91(anonymous function) @ js?callback=__google_maps_api_provider_initializator__:102(anonymous function) @ js?callback=__google_maps_api_provider_initializator__:46(anonymous function) @ js?callback=__google_maps_api_provider_initializator__:102hc @ js?callback=__google_maps_api_provider_initializator__:48gc.cb @ js?callback=__google_maps_api_provider_initializator__:102(anonymous function) @ map.js:1`

**Comment by davidkudera** [comment]
Hi, this library was written for commonjs modules, not for es6 modules.

So the first line should be actually `import GoogleMapsLoader = require('google-maps');`.

Also you should set all options (like `KEY`) in some bootstrap file. Otherwise you'll have to set options in all files where you want to use this library again and again.

**Comment by Caoimhin89** [comment]
Thanks, that makes sense.

**Comment by davidkudera** [comment]
Closing for now, if you'll have any other problem, just ask :wink:
