### ISSUE TITLE
need to Add channel Paremeter 

### ISSUE THREAD

**Issue by ReneeLai** [Carrooi/Js-GoogleMapsLoader#46]
When using the JavaScript API with a Google Maps APIs Premium Plan license.

custormer may add the channel parameter to requests so they can view more detailed usage reports

https://developers.google.com/maps/documentation/javascript/get-api-key#prev-license

but I can't add channel paremeter by `GoogleMapsLoader`

**Comment by ReneeLai** [comment]
sorry , I typed in wrong word case.

it should be 
`GoogleMapsLoader.CHANNEL = XXX; `

I  used to use lowercase before . my fault 
It works!!

**Comment by davidkudera** [comment]
good to hear that :+1:
