### ISSUE TITLE
Errors in IDE

### ISSUE THREAD

**Issue by piernik** [Carrooi/Js-GoogleMapsLoader#47]
I'm using Your types in PHPStorm IDE, and it throws error:
![googlemapsloader](https://cloud.githubusercontent.com/assets/420691/22966938/9b845770-f364-11e6-8e42-7d8427906600.png)

I have typescript 2.1.5

**Comment by davidkudera** [comment]
Hi, how do you import this library?

**Comment by piernik** [comment]
`import * as GoogleMapsLoader from "google-maps";`

**Comment by davidkudera** [comment]
This library is using commonjs loading, not es6.

Try `import GoogleMapsLoader = require('google-maps');` and it should work

**Comment by piernik** [comment]
It does work... Thanks
