### ISSUE TITLE
Assign API key

### ISSUE THREAD

**Issue by StephenPaul** [Carrooi/Js-GoogleMapsLoader#50]
Hi, I am building an Angular2 / typescript app using the Angular CLI. 
I installed the typings and it seems to be working.
I'm trying to set the `KEY`, statically, as per the docs:
`GoogleMapsLoader.KEY = 'myApiKey';`
It seems that property is read-only, I get the following compilation error:

> Left-hand side of assignment expression cannot be a constant or a read-only property

Am I missing something obvious?

**Comment by davidkudera** [comment]
Hi, how do you import this library?

**Comment by StephenPaul** [comment]
Thanks for your response, like so:
import * as GoogleMapsLoader from 'google-maps';

**Comment by davidkudera** [comment]
You should import it like this:

```typescript
import googleMapsLoader = require('google-maps');
```

Thats because this library was written just for common js loader, not for es6.

**Comment by StephenPaul** [comment]
Ah shucks,
Import assignment cannot be used when targeting ECMAScript 2015 modules, which I believe I have to.
Everything else seems to work (I only get a warning) I just can't assign the API key 
Thanks so much for your time anyway ;)

**Comment by davidkudera** [comment]
I see, in my typescript apps I target es5 so thats probably why it works for me even when I combine es5 and es6 modules together..

Anyway in a future I plan to rewrite this library to typescript and use es6 loading, so stay tuned :wink:
