### ISSUE TITLE
We're getting a warning that google maps version 3.31 is retired.

### ISSUE THREAD

**Issue by mikeabiezzi** [Carrooi/Js-GoogleMapsLoader#65]
```WARN: 'Google Maps JavaScript API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version'```

Happy to submit a PR with some instruction.

**Comment by davidkudera** [comment]
Hi and thanks for reporting. PR would be appreciated.

It should be enough to just change this line: https://github.com/Carrooi/Js-GoogleMapsLoader/blob/master/lib/Google.js#L21

and run `npm run minify`.

**Comment by freddyamsterdam** [comment]
@davidkudera PR submitted.

... also, just setting the version like so ```GoogleMapsLoader.VERSION = 3.34``` seems to do the trick.

**Comment by jrgcubano** [comment]
hi there.. and the release in npm?

**Comment by davidkudera** [comment]
@jrgcubano just require a specific git commit for now

```json
"dependencies": {
    "google-maps": "git@github.com:Carrooi/Js-GoogleMapsLoader.git#ff66b0645fe2e32d7bde6a272281355e10b3e0a4"
}
```
