### ISSUE TITLE
Google Maps JavaScript API warning

### ISSUE THREAD

**Issue by mosherimok** [Carrooi/Js-GoogleMapsLoader#69]
I got that warning:
util.js:224 Google Maps JavaScript API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version

every time I try to load a Google Map

**Comment by davidkudera** [comment]
fixed with ff66b0645fe2e32d7bde6a272281355e10b3e0a4

**Comment by schellenbergk** [comment]
How do I install this commit with npm?  `npm i google-maps@latest` installs only up to 3.3.0.
